version: '3.8'

services:
  vpn-portal:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # You can override .env values here if needed
    restart: unless-stopped
    volumes:
      # For persistence (if needed)
      - ./data:/app/data